main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('accounts/signup/', views.signup, name='signup'),
    path('', views.PropertyList.as_view(), name='home'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile_view'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
    path('profile/<int:pk>/delete/', views.ProfileDelete.as_view(), name='profile_delete'),
    path('profile/<int:user_id>/add_profile_photo/', views.add_profile_photo, name='add_profile_photo'),
    path('property/<int:property_id>/', views.property_detail, name='property_detail'),
    path('property/create_property/', views.PropertyCreate.as_view(), name='create_property'),
    path('property/<int:pk>/update/', views.PropertyUpdate.as_view(), name='property_update'),
    path('property/<int:pk>/delete/', views.PropertyDelete.as_view(), name='property_delete'),
    path('property/<int:property_id>/associate_property_feature/<int:property_feature_id>/', views.associate_property_feature, name='associate_property_feature'),
    path('property/<int:property_id>/dissociate_property_feature/<int:property_feature_id>/', views.dissociate_property_feature, name='dissociate_property_feature'),
    path('property/<int:property_id>/add_photo/', views.add_photo, name='add_photo'),
    path('property/<int:property_id>/delete_photo/', views.delete_photo_page, name='delete_photo_page'),
    path('property/<int:property_id>/delete_photo/<int:photo_id>/', views.delete_photo, name='delete_photo'),
    path('property/<int:property_id>/add_availability/', views.add_availability, name="add_availability"),
    path('property/<int:property_id>/delete_availability/<int:availability_id>/', views.delete_availability, name='delete_availability'),
    path('property/<int:property_id>/<int:pk>/update/', views.AvailabiblityUpdate.as_view(), name="update_availability"),
    path('property/<int:property_id>/review_property/', views.review_property, name='review_property'),
    path('property/<int:pk>/host_profile/', views.HostProfileView.as_view(), name='host_profile_view'),
    path('property/<int:property_id>/add_like/', views.add_like,name="add_like"),
    path('property/<int:property_id>/remove_like/', views.remove_like, name="remove_like"),
    path('property/<int:property_id>/make_reservation/<int:availability_id>/', views.make_reservation, name='make_reservation'),
    path('property/<int:property_id>/cancel_reservation/<int:availability_id>/', views.cancel_reservation, name='cancel_reservation'),
    path('reservations/<int:user_id>/', views.reservation_list, name='reservation_list'),
]

nomadic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from enum import auto
from django.db import models
from django.forms import DateField
from django.urls import reverse
from datetime import datetime, date  
from django.contrib.auth.models import User


RATINGS = (
    ('E', 'Excellent'),
    ('VG', 'Very Good'),
    ('G', 'Good'),
    ('A', 'Average'),
    ('B', 'Bad'),
    ('VB', 'Very Bad'),
    ('S', 'Stay Away')
)

class ProfilePicture(models.Model):
    url = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo created for {self.user.username}"


class PropertyFeature(models.Model):
    feature = models.CharField(
        max_length=30,
    )
    
    def __str__(self):
        return f"{self.feature}"
    
    class Meta:
        ordering = ['feature']


class Property(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=1200)
    location = models.CharField(max_length=100)
    property_features = models.ManyToManyField(PropertyFeature)
    price = models.FloatField()
    date_listed = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} on {self.date_listed}"

    def get_absolute_url(self):
        return reverse('property_detail', kwargs={'property_id': self.id})

    class Meta:
        ordering = ['-date_listed']


class Photo(models.Model):
    photo_url = models.CharField(max_length=200)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Photo created for {self.property.title} on {self.date_created}"

    class Meta:
        ordering = ['date_created']


class Availability(models.Model):
    from_date = models.DateField('Available from')
    till_date = models.DateField('Available till')
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.from_date} to {self.till_date} for {self.property.title}"

    class Meta:
        ordering = ['from_date']
    
    def get_absolute_url(self):
        return reverse('property_detail', kwargs={'property_id': self.property.id})


class Like(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return  f"{self.user.username} likes {self.property.title}"


class Review(models.Model):
    user_name = models.CharField(max_length=100)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    rating = models.CharField(
        max_length=2,
        choices = RATINGS,
    )
    review_text = models.TextField(max_length=800)
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"By {self.user_name} on {self.date}"

    class Meta:
        ordering = ['-date']


class Reservation(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    availability = models.ForeignKey(Availability, on_delete = models.CASCADE)
    property = models.ForeignKey(Property, on_delete = models.CASCADE)
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return f"{self.user} made reservation on {self.availability} "
    
    class Meta:
        ordering = ['date']

main_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse

from django.forms import ModelForm
from main_app.models import Availability, Review,Like


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    
    def __init__(self, *args, **kwargs):
        super(NewUserForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")


class DateInput(forms.DateInput):
    input_type = 'date'


class AvailabilityForm(ModelForm):
    class Meta:
        model = Availability
        fields = ["from_date","till_date"]
        widgets = {
            "from_date" : forms.DateInput(attrs = {'id' : 'id_from_date' , 'type' : 'date'}),
            "till_date" : forms.DateInput(attrs = {'id' : 'id_till_date' , 'type' : 'date'}), 
        }


class PropertyReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'review_text']


class LikeForm(ModelForm):
    class Meta:
        model = Like
        fields = "__all__"

main_app/views.py
import uuid
import boto3
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import NewUserForm, AvailabilityForm, PropertyReviewForm,LikeForm
from django.views.generic import ListView, DeleteView, DetailView, UpdateView, CreateView
from django.contrib import messages
from .models import ProfilePicture, User, Property, PropertyFeature, Photo, Availability, Like, Review,Reservation
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt

S3_BASE_URL = 'https://s3-ca-central-1.amazonaws.com/'
BUCKET = 'nomadic-project'



def signup(request):
  error_message = ''
  if request.method == 'POST':
    # Create a 'user' form object that includes the data from the browser
    form = NewUserForm(request.POST)
    if form.is_valid():
      # Add the user to the database
      user = form.save()
      # Login after signing up
      login(request, user)
      return redirect('profile_view', pk = user.id)
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = NewUserForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


class ProfileView(LoginRequiredMixin, DetailView):
  model = User
  template_name = 'user/profile.html'


class ProfileUpdate(LoginRequiredMixin, UpdateView):
  model = User
  template_name = 'user/updateuser.html'
  fields = ['email']
  success_url = '/'


class ProfileDelete(LoginRequiredMixin, DeleteView):
  model = User
  template_name = 'user/confirm_delete.html'
  success_url = '/'


class PropertyList(ListView):
  model = Property
  template_name = 'property/index.html'


@login_required
def property_detail(request, property_id):
  user_like = Like.objects.filter(property=property_id, user=request.user)
  property = Property.objects.get(id=property_id)
  not_available = Reservation.objects.filter(property = property_id).values_list('availability', flat=True)
  reservation_user = Reservation.objects.filter(property = property_id, user=request.user).values_list('user', flat=True)
  property_review_form = PropertyReviewForm
  features_property_doesnt_have = PropertyFeature.objects.exclude(id__in = property.property_features.all().values_list('id'))
  features_property_doesnt_have_id = PropertyFeature.objects.exclude(id__in = property.property_features.all().values_list('id')).values_list("id", flat=True)
  availability_form = AvailabilityForm
  return render(request, 'property/detail.html',{
    'property': property,
    'features_property_doesnt_have': features_property_doesnt_have,
    'availability_form' : availability_form,
    'property_review_form' : property_review_form,
    'user_like': user_like,
    'not_available' : not_available,
    'reservation_user': reservation_user,
    'features_property_doesnt_have_id': features_property_doesnt_have_id
  })


class PropertyCreate(LoginRequiredMixin, CreateView):
  model = Property
  fields = ['title', 'description', 'location', 'price']
  template_name = 'property/createproperty.html'
  def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PropertyUpdate(LoginRequiredMixin, UpdateView):
  model = Property
  fields = ['title', 'description', 'location', 'price']
  template_name = 'property/createproperty.html'


class PropertyDelete(LoginRequiredMixin, DeleteView):
  model = Property
  template_name = 'property/confirm_delete.html'
  success_url = '/'


@login_required
def associate_property_feature(request, property_id, property_feature_id):
  Property.objects.get(id=property_id).property_features.add(property_feature_id)
  return redirect('property_detail', property_id=property_id)


@login_required
def dissociate_property_feature(request, property_id, property_feature_id):
  Property.objects.get(id=property_id).property_features.remove(property_feature_id)
  return redirect('property_detail', property_id=property_id)


@login_required
def add_photo(request, property_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
      s3 = boto3.client('s3')
      # need a unique "key" for S3 / needs image file extension too
      key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
      try:
          s3.upload_fileobj(photo_file, BUCKET, key)
          # build the full url string
          url = f"{S3_BASE_URL}{BUCKET}/{key}"
          # we can assign to property_id or property (if you have a property object)
          photo = Photo(photo_url=url, property_id=property_id)
          photo.save()
      except:
          print('An error occurred uploading file to S3')
  return redirect('property_detail', property_id=property_id)


@login_required
def delete_photo_page(request, property_id):
  property = Property.objects.get(id=property_id)
  return render(request, 'property/property_photos.html',{
    'property': property,
  })


@login_required
def delete_photo(request, property_id, photo_id):
  Property.objects.get(id = property_id).photo_set.filter(id = photo_id).delete()
  return redirect('delete_photo_page', property_id = property_id)


@login_required
def add_profile_photo(request, user_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        # First delete previous photo (Only one photo is allowed)
        existing_photos = ProfilePicture.objects.filter(user_id=user_id)
        if existing_photos:
            existing_photos.delete()
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to user_id or user (if you have a user object)
            profile_picture = ProfilePicture(url=url, user_id=user_id)
            profile_picture.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('profile_view', pk=user_id)


@login_required
def add_availability(request, property_id):
  form = AvailabilityForm(request.POST)
  if form.is_valid():
    new_availbility = form.save(commit=False)
    new_availbility.property_id = property_id
    new_availbility.save()
  return redirect('property_detail', property_id = property_id)


@login_required
def delete_availability(request, property_id, availability_id):
  Property.objects.get(id = property_id).availability_set.filter(id = availability_id).delete()
  return redirect('property_detail', property_id = property_id)


class AvailabiblityUpdate(LoginRequiredMixin, UpdateView):
  model = Availability
  form_class = AvailabilityForm
  template_name = 'property/availability_form.html'


@login_required
def review_property(request, property_id):
    form = PropertyReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.user_name = request.user.username
        new_review.property_id = property_id
        new_review.save()
    return redirect('property_detail', property_id = property_id)


class HostProfileView(LoginRequiredMixin, DetailView):
  model = Property
  template_name = 'property/host_profile.html'


@login_required
def add_like(request, property_id):
    property = Property.objects.get(id = property_id)
    user = request.user
    if not Like.objects.filter(property = property, user = user).exists():
      new_like = Like(property = property, user = user)
      new_like.save()
    return redirect('property_detail', property_id = property_id)


@login_required
def remove_like(request,property_id):
  property = Property.objects.get(id = property_id)
  user = request.user
  if Like.objects.filter(property = property, user = user).exists():
     Like.objects.filter(property = property, user = user).delete()
  return redirect('property_detail', property_id = property_id)


@login_required
def make_reservation(request, property_id, availability_id):
  availability = Availability.objects.get(id = availability_id)
  user = request.user
  property = Property.objects.get(id = property_id)
  if not Reservation.objects.filter(availability = availability).exists():
    new_reservation = Reservation(availability = availability, user = user, property = property)
    new_reservation.save()
  return redirect('property_detail', property_id = property_id)


@login_required
def cancel_reservation(request, property_id, availability_id):
  if Reservation.objects.filter(availability = availability_id).exists():
     Reservation.objects.filter(availability = availability_id).delete()
  return redirect('property_detail', property_id = property_id)


@login_required
def reservation_list(request, user_id):
  reservation_list = Reservation.objects.all()
  context = {'reservation_list': reservation_list}
  return render(request, 'user/reservations.html', context)

main_app/templates/user/confirm_delete.html
{% extends 'base.html' %}

{% block title%}
    <h2>Delete User</h2>
{% endblock %}

{% block content %}
    <h1>Delete user: {{ user.username }}</h1>
    <h4>Are you sure you want to delete this user?</h4>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete" class="btn btn-danger">
        <a href="{% url 'profile_view' user.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/user/profile.html
{% extends 'base.html' %}
{% block title%}
    <h3>{{user.first_name}}'s Profile</h3>
{% endblock %}

{% block content %}

<div class="main-content mt-5">
    <div class="row">
        <div class="col-3 p-2">
            <div class="">
                {% for photo in user.profilepicture_set.all %}
                    <img class="profile-img img-thumbnail" src="{{photo.url}}">
                {% empty %}
                    <div class="card-panel center-align">No Photo</div>
                {% endfor %}
            </div>
            {% if user == request.user %}
            <br>
            <div class="">
                <form action="{% url 'add_profile_photo' user.id %}" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <input type="file" name="photo-file">
                    <br><br>
                    <input type="submit" class="btn btn-sm btn-outline-primary" value="Update Photo">
                </form>
            </div>
            {% endif %}
        </div>
        <div class="col p-3">
            <h3>User Information</h3>
            <p><strong>Username: </strong>{{user.username}}</p>
            <p><strong>First Name: </strong>{{ user.first_name}}</p>
            <p><strong>Last Name: </strong>{{ user.last_name}}</p>
            <p><strong>Email: </strong>{{ user.email}}</p>
            
            {% if user.id == request.user.id %}
            <div class="">
                <a class="text-decoration-none" href="{% url 'profile_update' user.id %}"><button class="btn btn-primary">Edit</button></a>
                <a class="text-decoration-none" href="{% url 'profile_delete' user.id %}"><button class="btn btn-danger">Delete</button></a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="d-flex flex-row flex-wrap justify-content-between">
        <div class="card border-light m-1 p-0" style="width: 45%;">
            <div class="p-2 bg-light w-100">
                <h3 class="text-center">Posted Properties</h3>
            </div>
            <div class="p-3 mx-auto w-100 scroll">
                {% for property in user.property_set.all%}
                <a class="text-decoration-none text-center" href="{% url 'property_detail' property.id %}">
                    <div class="card flex-container profile-property-card" >
                        {% if property.photo_set.first %}
                        <div class="text-center">
                            <img class="profile-property-photo" src="{{property.photo_set.first.photo_url}}" alt="No image">
                        </div>
                        {% else %}
                        <div class="text-center text-dark">
                            <p>No Image</p>
                        </div>
                        {% endif %}
                    </div>
                    <div class="profile-card-text">
                        <p class="text-center text-dark"><strong>{{property.title}}</strong></p>
                        <p class="text-center text-dark">{{property.location}}</p>
                        <p class="text-center text-dark">{{property.price|floatformat:2}} CAD per night</p>
                    </div>
                </a>
                <br>
                {% empty %}
                <p>No Properties posted</p>
                {% endfor %}
            </div>

        </div>
        <div class="card border-light m-1 p-0" style="width: 45%;">
            <div class="p-2 bg-light w-100">
                <h3 class="text-center">Liked Properties</h3>
            </div>
            <div class="p-3 mx-auto w-100 scroll">
                {% for like in user.like_set.all%}
                <a class="text-decoration-none text-center" href="{% url 'property_detail' like.property.id %}">
                    <div class="card flex-container profile-property-card" >
                        {% if like.property.photo_set.first %}
                        <div class="text-center">
                            <img class="profile-property-photo" src="{{like.property.photo_set.first.photo_url}}" alt="No image">
                        </div>
                        {% else %}
                        <div class="text-center text-dark">
                            <p>No Image</p>
                        </div>
                        {% endif %}
                    </div>
                    <div class="profile-card-text">
                        <p class="text-center text-dark"><strong>{{like.property.title}}</strong></p>
                        <p class="text-center text-dark">{{like.property.location}}</p>
                        <p class="text-center text-dark">{{like.property.price|floatformat:2}} CAD per night</p>
                    </div>
                </a>
                <br>
                {% empty %}
                <p>No Properties Liked</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
</div>

{% endblock %}

main_app/templates/user/reservations.html
{% extends 'base.html' %}

{% block title%}
<h3>Reservation History</h3>
{% endblock %}

{% block content %}
<div class="main-content">
    <div class="reservation-page">
        <table class="table table-striped">
            <thead>
                <tr>
                  <th scope="col">Reservation Date</th>
                  <th scope="col">Property</th>
                  <th scope="col">From</th>
                  <th scope="col">Till</th>
                </tr>
            </thead>
            <tbody>
                {% for reservation in reservation_list %}
                    {% if reservation.user.id == user.id %}
                    <tr>
                        <td>{{reservation.date}}</td>
                        <td><a  class="text-decoration-none" href="{% url 'property_detail' reservation.property.id %}">{{reservation.property.title}}</a></td>
                        <td>{{reservation.availability.from_date}}</td>
                        <td>{{reservation.availability.till_date}}</td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

main_app/templates/user/updateuser.html
{% extends 'base.html' %}

{% block title%}
    <h3>Edit User</h3>
{% endblock %}

{% block content %}
<div class="p-5 border-light container justify-content-center">
    <div class=" w-50 card row justify-content-center mx-auto">
        <div class="col bg-light">
            <h3 class="text-center mt-2">Edit <span class="teal-text">{{user.username}}</span></h3>
            <br>
            <div class="p-3 text-center">
                <form method="post" action="">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Submit">
                </form>
            </div>
        </div>
    </div>
</div>


    

{% endblock %}